### ISSUE TITLE
PHP 7.4 magic

### ISSUE THREAD

**Issue by vanilium** [pacoogle/laravel-lumen-docker#5]
Hi.
Thanks for the script, it is simple and working.
I noticed one oddity. If you run as it is, everything works. But if you replace the PHP version to version 7.4, the installation will break, demanding installing oniguruma. I added to the script
`RUN apk update
RUN apk add oniguruma-dev`
and everything worked. I don't know why with version 7.3 everything works, but for 7.4 I had to modify the script

**Comment by pacoogle** [comment]
hi @vanilium thank you for updating. Can you open PR on my repo? Can you star my repo :-) ?

**Comment by pacoogle** [comment]
@vanilium I upgrade php version & Lumen version. Thank you for your reporting
